openapi: 3.0.1
info:
  title: AllOfUs Public API
  description: |
    The API for the AllOfUs databrowser.

    Throughout, we use integer/int64 in preference to string/date-time because Swagger's
    date formatting is inconsistent between server and client. Time values are stored as
    milliseconds since the UNIX epoch.

  termsOfService: http://www.pmi-ops.org/terms_of_service.html
  contact:
    name: developer_help@pmi-ops.org
  license:
    name: BSD
  version: 0.1.0
servers:
  - url: https://api.pmi-ops.org/
security:
  - aou_oauth: []

##########################################################################################
## PATHS
##########################################################################################
paths:
  /v1/me:
    get:
      tags:
        - profile
      description: Returns the user's profile information
      operationId: getMe
      responses:
        200:
          description: The user's profile.
          schema:
            $ref: "#/definitions/Profile"

definitions:
  Profile:
    type: object
    required:
      - username
      - dataAccessLevel
    properties:
      username:
        description: researchallofus username
        type: string
      dataAccessLevel:
        description: what level of data access the user has
        $ref: "#/definitions/DataAccessLevel"
      idVerificationStatus:
        $ref: "#/definitions/IdVerificationStatus"
        description: Status of ID verification

  IdVerificationStatus:
    type: string
    description: possible values indicating whether the user's ID has been verified
    enum: [UNVERIFIED, VERIFIED, REJECTED]

  DataAccessLevel:
      type: string
      description: levels of access to data in the curated data repository
      enum:
      - unregistered
      - registered
      - protected
      - revoked