openapi: 3.0.1
info:
  title: AllOfUs Workbench API
  description: The API for the AllOfUs workbench.
  termsOfService: http://www.pmi-ops.org/terms_of_service.html
  contact:
    name: developer_help@pmi-ops.org
  license:
    name: BSD
  version: 0.1.0
servers:
  - url: https://api.pmi-ops.org/
security:
  - aou_oauth: []
paths:
  /v1/me:
    get:
      tags:
        - profile
      description: Returns the user's profile information
      operationId: getMe
      responses:
        "200":
          description: The user's profile.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
components:
  schemas:
    Profile:
      required:
        - dataAccessLevel
        - username
      type: object
      properties:
        username:
          type: string
          description: researchallofus username
        dataAccessLevel:
          $ref: '#/components/schemas/DataAccessLevel'
        idVerificationStatus:
          $ref: '#/components/schemas/IdVerificationStatus'
    IdVerificationStatus:
      type: string
      description: possible values indicating whether the user's ID has been verified
      enum:
        - UNVERIFIED
        - VERIFIED
        - REJECTED
    DataAccessLevel:
      type: string
      description: levels of access to data in the curated data repository
      enum:
        - unregistered
        - registered
        - protected
        - revoked
  securitySchemes:
    aou_oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ""
          tokenUrl: ""
          scopes: {}
x-original-swagger-version: "2.0"
