openapi: 3.0.1
info:
  title: AllOfUs Public API
  description: |
    The API for the AllOfUs databrowser.
    Throughout, we use integer/int64 in preference to string/date-time because Swagger's
    date formatting is inconsistent between server and client. Time values are stored as
    milliseconds since the UNIX epoch.
  termsOfService: http://www.pmi-ops.org/terms_of_service.html
  contact:
    name: developer_help@pmi-ops.org
  license:
    name: BSD
  version: 0.1.0
servers:
  - url: https://api.pmi-ops.org/
security:
  - aou_oauth: []

paths:
  /v1/cdrVersions:
    get:
      tags:
        - cdrVersions
      description: Returns all curated data repository (CDR) versions that the user has access to
      operationId: getCdrVersions
      security: []
      responses:
        200:
          description: A list of CDR versions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CdrVersionListResponse"

components:
  schemas:
