openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /v1/cdrVersions:
    get:
      summary: Returns a list of cdr versions.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A list of cdr versions
          content:
            application/json:
              schema:
                $ref: "#/definitions/CdrVersionListResponse"

components:
  schemas:
    CdrVersion:
      type: object
      properties:
        cdrVersionId:
          type: string
        name:
          type: string
        numParticipants:
          type: integer
          format: int32
        creationTime:
          type: integer
          format: int64
          description: Milliseconds since the UNIX epoch.
      # Both properties are required
      required:
        - cdrVersionId
        - name
        - creationTime

    CdrVersionListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/definitions/CdrVersion"
        defaultCdrVersionId:
          type: string
          description: ID of the CDR versions that should be used by the user by default
      required:
        - items
        - defaultCdrVersionId
