CREATE DATABASE IF NOT EXISTS research_directory CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES, CREATE VIEW ON research-directory.* TO '${LIQUIBASE_DB_USER}'@'%';
