CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE USER IF NOT EXISTS '${DATABROWSER_DB_USER}'@'%' IDENTIFIED BY '${DATABROWSER_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${LIQUIBASE_DB_USER}'@'%' IDENTIFIED BY '${LIQUIBASE_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${PUBLIC_DB_USER}'@'%' IDENTIFIED BY '${PUBLIC_DB_PASSWORD}';
-- In case the users already exist, change their passwords.
SET PASSWORD FOR '${DATABROWSER_DB_USER}'@'%' = '${DATABROWSER_DB_PASSWORD}';
SET PASSWORD FOR '${LIQUIBASE_DB_USER}'@'%' = '${LIQUIBASE_DB_PASSWORD}';
SET PASSWORD FOR '${PUBLIC_DB_USER}'@'%' = '${PUBLIC_DB_PASSWORD}';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON ${DB_NAME}.* TO '${DATABROWSER_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, INDEX, REFERENCES, CREATE TEMPORARY TABLES, CREATE VIEW ON ${DB_NAME}.* TO '${LIQUIBASE_DB_USER}'@'%';

-- Give wildcard permission to public databases for public user
-- public matches the older naming convention + local
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON `public%`.* TO '${PUBLIC_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON `public%`.* TO '${DATABROWSER_DB_USER}'@'%';
-- {synth_,}p_ match the new naming convention
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON `p_%`.* TO '${PUBLIC_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON `synth_p_%`.* TO '${PUBLIC_DB_USER}'@'%';

-- {synth_,}p_ match the new naming convention
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON `p_%`.* TO '${DATABROWSER_DB_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON `synth_p_%`.* TO '${DATABROWSER_DB_USER}'@'%';
