export const environment = {
  displayTag: "Staging",
  publicApiUrl: "https://public.api.staging.fake-research-aou.org",
  researchAllOfUsUrl: "https://researchallofus.org",
  debug: false,
  gaId: "UA-116298798-4",
  gtmId: "GTM-NQ9XDTW",
  gtmAuth: "v5hD4oOWvct1sYdnaNp7yQ",
  gtmPreview: "env-28",
  reactSurveyTable: false,
  ehrReact: true,
  testReact: false,
  geno: true,
  genoFilters: true,
  fitbitCDRUpdate: true,
  infiniteSrcoll: true,
  svVCFBrowser: false,
  heatmap: true,
  combinedAgeGenderChart: true,
  geneLeads: false,
};
