runtime: nodejs22
default_expiration: "2m"
handlers:
- url: /(.*\.(css|eot|gz|html|ico|jpg|jpeg|js|map|png|svg|ttf|woff|woff2|pdf|mp4|webm|ogv|vtt))
  static_files: dist/\1
  upload: dist/(.*)
  secure: always
  # TODO(calbach): Bump max-age to 1y once we've verified this is correct.
  http_headers:
    Access-Control-Allow-Headers: origin, x-requested-with, content-type, accept
    Access-Control-Allow-Methods: GET, POST, OPTIONS
    Strict-Transport-Security: "max-age=86400; includeSubDomains; preload"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1"
    X-Frame-Options: "SAMEORIGIN"
    Content-Security-Policy: "default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com https://www.stable.researchallofus.org https://www.staging.researchallofus.org; frame-ancestors 'self'; font-src 'self' data: https://kit-pro.fontawesome.com https://kit-free.fontawesome.com https://ka-p.fontawesome.com;"

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Access-Control-Allow-Headers: origin, x-requested-with, content-type, accept
    Access-Control-Allow-Methods: GET, POST, OPTIONS
    Strict-Transport-Security: "max-age=86400; includeSubDomains; preload"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1"
    X-Frame-Options: "SAMEORIGIN"
    Content-Security-Policy: "default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com https://www.googletagmanager.com https://www.stable.researchallofus.org https://www.staging.researchallofus.org; frame-ancestors 'self'; font-src 'self' data: https://kit-pro.fontawesome.com https://kit-free.fontawesome.com https://ka-p.fontawesome.com;"

